<a href="https://colab.research.google.com/github/C4viar/PPD_MSLD_2019_2020_LL-AL-MT/blob/master/Draft_code/projet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 1

1. Reproduire avec l’implémentation
https://huggingface.co/transformers/model_doc/camembert.html
les manipulations décrites dans https://github.com/pytorch/fairseq/tree/master/examples/camembert

## CamemBERT

Rappel : Tous les types de modèles : https://huggingface.co/models

In [1]:
! pip install transformers;

     |████████████████████████████████| 573kB 2.8MB/s 
     |████████████████████████████████| 3.7MB 52.5MB/s 
     |████████████████████████████████| 1.0MB 54.1MB/s 
     |████████████████████████████████| 890kB 52.9MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.41-cp36-none-any.whl size=893334 sha256=e886f65b85900a8db557b892ce0b996bfddc6fcaa61f02068f5ce01948857859
  Stored in directory: /root/.cache/pip/wheels/22/5a/d4/b020a81249de7dc63758a34222feaa668dbe8ebfe9170cc9b1
Successfully built sacremoses


#### Fill mask

In [0]:
from transformers import pipeline, CamembertModel, CamembertTokenizer, CamembertForMaskedLM, PreTrainedModel


sentence_fillmask = """Le camembert c'est <mask>""".lstrip()
model_fillmask_str = "camembert-base"
model_fillmask = CamembertForMaskedLM.from_pretrained(model_fillmask_str)
tokenizer_fillmask = CamembertTokenizer.from_pretrained(model_fillmask_str)


fill_mask = pipeline(
    "fill-mask",
    model = model_fillmask,
    tokenizer = tokenizer_fillmask 
    )

fill_mask(sentence_fillmask)

[{'score': 0.2072705626487732,
  'sequence': "<s> Le camembert c'est quoi</s>",
  'token': 484},
 {'score': 0.08772061765193939,
  'sequence': "<s> Le camembert c'est bon</s>",
  'token': 212},
 {'score': 0.05717896297574043,
  'sequence': "<s> Le camembert c'est délicieux</s>",
  'token': 7200},
 {'score': 0.05560891702771187,
  'sequence': "<s> Le camembert c'est...</s>",
  'token': 186},
 {'score': 0.05323265120387077,
  'sequence': "<s> Le camembert c'est :</s>",
  'token': 43}]

#### Sentiment analysis

In [6]:
from transformers import CamembertForSequenceClassification, CamembertTokenizer, pipeline

sentence_sentiment = "Le camembert c'est bon"

model_sentiment_str = "camembert/camembert-large"
model_sentiment = CamembertForSequenceClassification.from_pretrained(model_sentiment_str)
tokenizer_sentiment = CamembertTokenizer.from_pretrained(model_sentiment_str )

sentiment_analysis = pipeline(
    "sentiment-analysis",
    model = model_sentiment,
    tokenizer = tokenizer_sentiment
    )

sentiment_analysis(sentence_sentiment)

[{'label': 'LABEL_0', 'score': 0.5135105}]

#### NER

Indisponible avec Camembert

In [8]:
from transformers import CamembertForTokenClassification

sentence_ner = "Amar habite à Paris"

ner_model_str = 'camembert/camembert-large'
ner_model = CamembertForTokenClassification.from_pretrained(ner_model_str)
tokenizer_ner= CamembertTokenizer.from_pretrained(ner_model_str)

ner = pipeline(
    "ner",
    model = ner_model,
    tokenizer = tokenizer_ner
    )

ner(sentence_ner)

[{'entity': 'LABEL_1', 'score': 0.5980371832847595, 'word': '<s>'},
 {'entity': 'LABEL_0', 'score': 0.5633740425109863, 'word': '▁Amar'},
 {'entity': 'LABEL_0', 'score': 0.5848187804222107, 'word': '▁habite'},
 {'entity': 'LABEL_0', 'score': 0.5327739119529724, 'word': '▁à'},
 {'entity': 'LABEL_0', 'score': 0.5927239060401917, 'word': '▁Paris'},
 {'entity': 'LABEL_1', 'score': 0.5606414675712585, 'word': '</s>'}]

#### Question answering

In [13]:
from transformers import CamembertModel

quest_model_str = 'camembert/camembert-base-ccnet'
quest_model = CamembertModel.from_pretrained(quest_model_str)  # XXXXXXX à remplacer / ! \
tokenizer_quest= CamembertTokenizer.from_pretrained(quest_model_str)

quest = pipeline(
    "question-answering",
    model = quest_model,
    tokenizer = tokenizer_quest
    )

quest({
    'question' : "Où habite Amar ?" ,
    'context' : "Amar habite à Paris."
    }
)

add example index and unique id: 100%|██████████| 1/1 [00:00<00:00, 2096.10it/s]


ValueError: ignored

#### Translation

#### Feature extraction

In [0]:
feature_extraction = pipeline(
    "feature-extraction",
    model = model_camembert,
    tokenizer = tokenizer_camembert
    )

feature_extraction(sentence)

#### Extract All-layers

In [0]:
input_ids = torch.tensor(tokenizer.encode(sentence, add_special_tokens=True)).unsqueeze(0)
labels = torch.tensor([1] * input_ids.size(1)).unsqueeze(0)

In [0]:
outputs_camembert = model(input_ids)

In [0]:
outputs_cammebert

(tensor([[[ 20.6235,  -4.2011,   6.8420,  ...,  -5.7573,  -3.1165,   1.1391],
          [  2.6217,  -5.2430,  17.5290,  ..., -14.2041,  -2.4229,   0.8586],
          [ -0.1691,  -9.8924,   1.8213,  ..., -22.9433, -11.8068,  -1.9409],
          ...,
          [ -0.6569, -10.2129,  -0.5032,  ...,  -7.7102, -10.5380,   1.3649],
          [ -1.6542,  -4.3773,   2.8810,  ...,  -7.5383,  -3.0471,  -3.1600],
          [  6.3686,  -5.1610,  23.3708,  ...,  -7.9306,  -5.1287,   1.9971]]],
        grad_fn=<AddBackward0>),)

## FlauBERT
### Ne fonctionne pas pour le moment

In [0]:
from transformers import FlaubertModel, AutoTokenizer, AutoModelWithLMHead

flaubert = "flaubert-large-cased"

tokenizer_flaubert = AutoTokenizer.from_pretrained(flaubert)
model_flaubert = AutoModelWithLMHead.from_pretrained(flaubert)


fill_mask = pipeline(
    "fill-mask",
    model = flaubert,
    tokenizer = flaubert
)

fill_mask(sentence)

### Flaubert : essai 2

In [0]:

import torch
from transformers import FlaubertModel, FlaubertTokenizer

# Choose among ['flaubert-small-cased', 'flaubert-base-uncased', 'flaubert-base-cased', 'flaubert-large-cased']
modelname = 'flaubert-base-cased' 

# Load pretrained model and tokenizer
flaubert, log = FlaubertModel.from_pretrained(modelname, output_loading_info=True)
flaubert_tokenizer = FlaubertTokenizer.from_pretrained(modelname, do_lowercase=False)
# do_lowercase=False if using cased models, True if using uncased ones

sentence = "Le camembert c'est <mask>."
token_ids = torch.tensor([flaubert_tokenizer.encode(sentence)])

fill_mask = pipeline(
    "fill-mask",
    model = flaubert,
    tokenizer = flaubert_tokenizer
)

fill_mask(sentence)

#last_layer = flaubert(token_ids)[0]
#print(last_layer.shape)
# torch.Size([1, 8, 768])  -> (batch size x number of tokens x embedding dimension)

# The BERT [CLS] token correspond to the first hidden state of the last layer
#cls_embedding = last_layer[:, 0, :]

#### TEST

In [14]:
from transformers import BertTokenizer, BertForMaskedLM
import torch

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForMaskedLM.from_pretrained('bert-base-uncased')

input_ids = torch.tensor(tokenizer.encode("Hello, my dog is cute", add_special_tokens=True)).unsqueeze(0)  # Batch size 1
outputs = model(input_ids, masked_lm_labels=input_ids)

loss, prediction_scores = outputs[:2]

In [15]:
outputs

(tensor(6.6588, grad_fn=<NllLossBackward>),
 tensor([[[ -7.8962,  -7.8105,  -7.7903,  ...,  -7.0694,  -7.1693,  -4.3590],
          [ -8.4461,  -8.4401,  -8.5044,  ...,  -8.0625,  -7.9909,  -5.7160],
          [-15.2952, -15.4727, -15.5864,  ..., -12.9856, -11.7038, -11.4292],
          ...,
          [-14.0628, -14.2535, -14.3645,  ..., -12.7151, -11.1621, -10.2317],
          [-10.6576, -10.7892, -11.0402,  ..., -10.3233, -10.1578,  -3.7721],
          [-11.3383, -11.4590, -11.1768,  ...,  -9.2152,  -9.5209,  -9.5571]]],
        grad_fn=<AddBackward0>))

In [16]:
input_ids

tensor([[  101,  7592,  1010,  2026,  3899,  2003, 10140,   102]])

In [17]:
prediction_scores

tensor([[[ -7.8962,  -7.8105,  -7.7903,  ...,  -7.0694,  -7.1693,  -4.3590],
         [ -8.4461,  -8.4401,  -8.5044,  ...,  -8.0625,  -7.9909,  -5.7160],
         [-15.2952, -15.4727, -15.5864,  ..., -12.9856, -11.7038, -11.4292],
         ...,
         [-14.0628, -14.2535, -14.3645,  ..., -12.7151, -11.1621, -10.2317],
         [-10.6576, -10.7892, -11.0402,  ..., -10.3233, -10.1578,  -3.7721],
         [-11.3383, -11.4590, -11.1768,  ...,  -9.2152,  -9.5209,  -9.5571]]],
       grad_fn=<AddBackward0>)